CREATE TABLE "SCHEMA"."PROPOSAL" ("ID_PROPOSAL" NUMBER(9,0), "ID_PRODUCT" VARCHAR2(50 BYTE), "CREATE_DATE" DATE, "COD_PROPOSAL_TYPE" VARCHAR2(50 BYTE), "LIBPROD" VARCHAR2(50 BYTE), "FLAG_EXP" NUMBER(1,0), "NB_HYP" NUMBER(9,0), "FLAG_AM" NUMBER(1,0), "FLAG_DURATION" NUMBER(1,0), "ID_PROPOSITION" VARCHAR2(50 BYTE), "MT_FINANCED" NUMBER(9,2), "NB_MONTH_" VARCHAR2(100 BYTE)) ; 

  CREATE TABLE "SCHEMA"."CONTRACT" ("ID_CONTRACT" NUMBER(9,0), "NB_DURATION_IN_MONTHS" NUMBER(9,0), "TX" NUMBER(9,4), "MT_ORIG" NUMBER(9,2), "MT_MONTH" NUMBER(9,2), "NB_DURATION_MONTH" NUMBER(9,0), "TX_TA" NUMBER(9,4), "COD_PERIOD" VARCHAR2(50 BYTE), "ID_CATEGORY" NUMBER(9,0), "ID_TYPE_CONTRACT" NUMBER(9,0), "ID_PROPOSAL" NUMBER(9,0), "COD_RANK" NUMBER(1,0), "ID_PRODUCT" VARCHAR2(50 BYTE)) ;  
  
  CREATE TABLE "SCHEMA"."CATEGORY" ("ID_CATEGORY" NUMBER(9,0), "COD_ACCOUNTING" VARCHAR2(50 BYTE), "LIB_CATEGORY" VARCHAR2(50 BYTE)) ;  

  CREATE TABLE "SCHEMA"."TYPE_CONTRACT" ("ID_TYPE_CONTRACT" NUMBER(9,0), "COD_ACCOUNT" VARCHAR2(50 BYTE), "LIB_CONTRACT_OBJECT" VARCHAR2(520 BYTE)) ; 

  ALTER TABLE "SCHEMA"."CONTRACT" ADD CONSTRAINT "PK_CONTRACT" PRIMARY KEY ("ID_CONTRACT") ENABLE;

  ALTER TABLE "SCHEMA"."CATEGORY" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY ("ID_CATEGORY") ENABLE;   

  ALTER TABLE "SCHEMA"."TYPE_CONTRACT" ADD CONSTRAINT "PK_TYPECONTRACT" PRIMARY KEY ("ID_TYPE_CONTRACT") ENABLE; 

  ALTER TABLE "SCHEMA"."CONTRACT" MODIFY ("ID_CONTRACT" NOT NULL ENABLE);   

  ALTER TABLE "SCHEMA"."CATEGORY" MODIFY ("ID_CATEGORY" NOT NULL ENABLE);

  ALTER TABLE "SCHEMA"."CATEGORY" MODIFY ("LIB_CATEGORY" NOT NULL ENABLE);   

  ALTER TABLE "SCHEMA"."TYPE_CONTRACT" MODIFY ("ID_TYPE_CONTRACT" NOT NULL ENABLE);  

  ALTER TABLE "SCHEMA"."TYPE_CONTRACT" MODIFY ("LIB_CONTRACT_OBJECT" NOT NULL ENABLE);

  ALTER TABLE "SCHEMA"."CONTRACT" ADD CONSTRAINT "FK_CONTRACT_PROPOSAL" FOREIGN KEY ("ID_PROPOSAL") REFERENCES "SCHEMA"."PROPOSAL" ("ID_PROPOSAL") ENABLE; 

  ALTER TABLE "SCHEMA"."CONTRACT" ADD CONSTRAINT "FK_CONTRACT_CATEGORY" FOREIGN KEY ("ID_CATEGORY") REFERENCES "SCHEMA"."CATEGORY" ("ID_CATEGORY") ENABLE;   

  ALTER TABLE "SCHEMA"."CONTRACT" ADD CONSTRAINT "FK_CONTRACT_TYPECONTRACT" FOREIGN KEY ("ID_TYPE_CONTRACT") REFERENCES "SCHEMA"."TYPE_CONTRACT" ("ID_TYPE_CONTRACT") ENABLE;

   CREATE SEQUENCE  "SCHEMA"."CONTRACT_ID_CONTRACT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11006 NOCACHE  NOORDER  NOCYCLE ;   



